//DEFINES
#define true 1
#define false 0
#define clear() printf("\e[1;1H\e[2J");
#define TIME "time"
#define HELLO "hello"
#define SETPSW "setpsw"
#define SETNAME "setname"
#define STOP "stop"
#define REMINDER "reminder"
#define GOOGLE "g"
#define YOUTUBE "yt"
#define STACKOVERFLOW "so"
#define WIKIPEDIA "wiki"
#define EDITOR "editor"
#define TERMINAL "terminal"
#define TODO "todo"
#define SKYPE "skype"
#define MUSIC "music"
#define CLEAR "clear"
#define SCHOOL "school"
#define DISCORD "discord"
#define GITHUB "github"
#define NOTES "notes"